// This was generated by ChatGPT

const http = require('http');
const fs = require('fs');
const path = require('path');

const port = 3000; // Change this to any desired port number

const server = http.createServer((req, res) => {
    // Check the requested URL and serve the appropriate file
    if (req.url === '/') {
        // Serve the HTML file
        const htmlFilePath = path.join(__dirname, 'match.html');
        fs.readFile(htmlFilePath, 'utf8', (err, data) => {
            if (err) {
                res.writeHead(500, { 'Content-Type': 'text/plain' });
                res.end('Internal Server Error');
            } else {
                res.writeHead(200, { 'Content-Type': 'text/html' });
                res.end(data);
            }
        });
    } else if (req.url.startsWith('/images/')) {
        // Serve images
        const imagePath = path.join(__dirname, req.url);
        fs.readFile(imagePath, (err, data) => {
            if (err) {
                res.writeHead(404, { 'Content-Type': 'text/plain' });
                res.end('Image not found');
            } else {
                res.writeHead(200, { 'Content-Type': 'image/jpeg' }); // Change the content type according to your image format
                res.end(data);
            }
        });
    } else {
        // Handle other requests
        res.writeHead(404, { 'Content-Type': 'text/plain' });
        res.end('Page not found');
    }
});

server.listen(port, () => {
    console.log(`Server is running at http://localhost:${port}/`);
});
